const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {validate, UpscaleManager} = require('../electron/upscale');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'hafez-upscale-test-'));
const input = path.join(root, 'video with spaces.mp4');
fs.writeFileSync(input, 'test fixture');
const p = {input, mode:'preview', resolution:1080, start:0};
assert.equal(validate(p).resolution, 1080);
assert.throws(() => validate({...p, resolution:999}));
assert.equal(validate({...p, mode:'full'}).directFullRequest,true);
assert.equal(validate({...p, mode:'full', start:5}).start,0);
assert.equal(validate({...p, mode:'full'}).qualityConfirmed,false);
assert.throws(() => validate({...p, start:NaN}));
assert.throws(() => validate({...p, input:root}));
const manager = new UpscaleManager({runtime:root, editingBusy:()=>true});
assert.equal(manager.status().installed, false);
assert.throws(() => manager.start(p), /ابتدا/);
assert.equal(manager.cancel(), false);
fs.writeFileSync(path.join(root,'active-job.json'), JSON.stringify({pid:process.pid}));
assert.equal(manager.externalBusy(),true);
assert.equal(manager.status().running,true);
console.log('Upscale direct full processing, validation and mutual-exclusion: 12 assertions passed');
